/**
 * Accepts either a country ID as a number or a country name as a string and
 * converts it to the opposite of the input. Designed to act as a helper
 * function that converts between a human-readable format or a
 * database-readable format, as is required.
 * @param input {Database["countries"]["country_id"]|Database["countries"]["name"]}
 * The input value, union typed as a value between 1 and 249 or a country between
 * Afghanistan and Zimbabwe. These types directly correspond with read-only values
 * within the database table "countries", and correspond to the "country_id" and
 * "name" columns, respectively. If an invalid value is entered, this function
 * will throw an error, as it is critical to reading and writing from the database.
 * @returns {Database["countries"]["name"]|Database["countries"]["country_id"]}
 * The return type is the converted opposite of the input.
 * @example
 * // Returns "Afghanistan"
 * convertCountry(1)
 * @example
 * // Returns 1
 * convertCountry("Afghanistan")
 */
export function convertCountry(
  input: CountryID | CountryName
): CountryName | CountryID {
  // Lookup label via ID
  const countryLabels: Record<CountryID, CountryName> = {
    1: "Afghanistan",
    2: "Åland Islands",
    3: "Albania",
    4: "Algeria",
    5: "American Samoa",
    6: "Andorra",
    7: "Angola",
    8: "Anguilla",
    9: "Antarctica",
    10: "Antigua and Barbuda",
    11: "Argentina",
    12: "Armenia",
    13: "Aruba",
    14: "Australia",
    15: "Austria",
    16: "Azerbaijan",
    17: "Bahamas",
    18: "Bahrain",
    19: "Bangladesh",
    20: "Barbados",
    21: "Belarus",
    22: "Belgium",
    23: "Belize",
    24: "Benin",
    25: "Bermuda",
    26: "Bhutan",
    27: "Bolivia",
    28: "Bonaire, Sint Eustatius and Saba",
    29: "Bosnia and Herzegovina",
    30: "Botswana",
    31: "Bouvet Island",
    32: "Brazil",
    33: "British Indian Ocean Territory",
    34: "Brunei Darussalam",
    35: "Bulgaria",
    36: "Burkina Faso",
    37: "Burundi",
    38: "Cambodia",
    39: "Cameroon",
    40: "Canada",
    41: "Cape Verde",
    42: "Cayman Islands",
    43: "Central African Republic",
    44: "Chad",
    45: "Chile",
    46: "China",
    47: "Christmas Island",
    48: "Cocos (Keeling) Islands",
    49: "Colombia",
    50: "Comoros",
    51: "Congo",
    52: "Congo, the Democratic Republic of the",
    53: "Cook Islands",
    54: "Costa Rica",
    55: "Cote DIvoire",
    56: "Croatia",
    57: "Cuba",
    58: "Curaçao",
    59: "Cyprus",
    60: "Czech Republic",
    61: "Denmark",
    62: "Djibouti",
    63: "Dominica",
    64: "Dominican Republic",
    65: "Ecuador",
    66: "Egypt",
    67: "El Salvador",
    68: "Equatorial Guinea",
    69: "Eritrea",
    70: "Estonia",
    71: "Ethiopia",
    72: "Falkland Islands (Malvinas)",
    73: "Faroe Islands",
    74: "Fiji",
    75: "Finland",
    76: "France",
    77: "French Guiana",
    78: "French Polynesia",
    79: "French Southern Territories",
    80: "Gabon",
    81: "Gambia",
    82: "Georgia",
    83: "Germany",
    84: "Ghana",
    85: "Gibraltar",
    86: "Greece",
    87: "Greenland",
    88: "Grenada",
    89: "Guadeloupe",
    90: "Guam",
    91: "Guatemala",
    92: "Guernsey",
    93: "Guinea",
    94: "Guinea-Bissau",
    95: "Guyana",
    96: "Haiti",
    97: "Heard Island and Mcdonald Islands",
    98: "Holy See (Vatican City State)",
    99: "Honduras",
    100: "Hong Kong",
    101: "Hungary",
    102: "Iceland",
    103: "India",
    104: "Indonesia",
    105: "Iran, Islamic Republic of",
    106: "Iraq",
    107: "Ireland",
    108: "Isle of Man",
    109: "Israel",
    110: "Italy",
    111: "Jamaica",
    112: "Japan",
    113: "Jersey",
    114: "Jordan",
    115: "Kazakhstan",
    116: "Kenya",
    117: "Kiribati",
    118: "Korea, Democratic People's Republic of",
    119: "Korea, Republic of",
    120: "Kuwait",
    121: "Kyrgyzstan",
    122: "Lao People's Democratic Republic",
    123: "Latvia",
    124: "Lebanon",
    125: "Lesotho",
    126: "Liberia",
    127: "Libya",
    128: "Liechtenstein",
    129: "Lithuania",
    130: "Luxembourg",
    131: "Macao",
    132: "Macedonia, the Former Yugoslav Republic of",
    133: "Madagascar",
    134: "Malawi",
    135: "Malaysia",
    136: "Maldives",
    137: "Mali",
    138: "Malta",
    139: "Marshall Islands",
    140: "Martinique",
    141: "Mauritania",
    142: "Mauritius",
    143: "Mayotte",
    144: "Mexico",
    145: "Micronesia, Federated States of",
    146: "Moldova, Republic of",
    147: "Monaco",
    148: "Mongolia",
    149: "Montenegro",
    150: "Montserrat",
    151: "Morocco",
    152: "Mozambique",
    153: "Myanmar",
    154: "Namibia",
    155: "Nauru",
    156: "Nepal",
    157: "Netherlands",
    158: "New Caledonia",
    159: "New Zealand",
    160: "Nicaragua",
    161: "Niger",
    162: "Nigeria",
    163: "Niue",
    164: "Norfolk Island",
    165: "Northern Mariana Islands",
    166: "Norway",
    167: "Oman",
    168: "Pakistan",
    169: "Palau",
    170: "Palestine, State of",
    171: "Panama",
    172: "Papua New Guinea",
    173: "Paraguay",
    174: "Peru",
    175: "Philippines",
    176: "Pitcairn",
    177: "Poland",
    178: "Portugal",
    179: "Puerto Rico",
    180: "Qatar",
    181: "Reunion",
    182: "Romania",
    183: "Russian Federation",
    184: "Rwanda",
    185: "Saint Barthélemy",
    186: "Saint Helena, Ascension and Tristan da Cunha",
    187: "Saint Kitts and Nevis",
    188: "Saint Lucia",
    189: "Saint Martin (French part)",
    190: "Saint Pierre and Miquelon",
    191: "Saint Vincent and the Grenadines",
    192: "Samoa",
    193: "San Marino",
    194: "Sao Tome and Principe",
    195: "Saudi Arabia",
    196: "Senegal",
    197: "Serbia",
    198: "Seychelles",
    199: "Sierra Leone",
    200: "Singapore",
    201: "Sint Maarten (Dutch part)",
    202: "Slovakia",
    203: "Slovenia",
    204: "Solomon Islands",
    205: "Somalia",
    206: "South Africa",
    207: "South Georgia and the South Sandwich Islands",
    208: "South Sudan",
    209: "Spain",
    210: "Sri Lanka",
    211: "Sudan",
    212: "Suriname",
    213: "Svalbard and Jan Mayen",
    214: "Swaziland",
    215: "Sweden",
    216: "Switzerland",
    217: "Syrian Arab Republic",
    218: "Taiwan (Province of China)",
    219: "Tajikistan",
    220: "Tanzania, United Republic of",
    221: "Thailand",
    222: "Timor-Leste",
    223: "Togo",
    224: "Tokelau",
    225: "Tonga",
    226: "Trinidad and Tobago",
    227: "Tunisia",
    228: "Turkey",
    229: "Turkmenistan",
    230: "Turks and Caicos Islands",
    231: "Tuvalu",
    232: "Uganda",
    233: "Ukraine",
    234: "United Arab Emirates",
    235: "United Kingdom",
    236: "United States",
    237: "United States Minor Outlying Islands",
    238: "Uruguay",
    239: "Uzbekistan",
    240: "Vanuatu",
    241: "Venezuela",
    242: "Viet Nam",
    243: "Virgin Islands (British)",
    244: "Virgin Islands (U.S.)",
    245: "Wallis and Futuna",
    246: "Western Sahara",
    247: "Yemen",
    248: "Zambia",
    249: "Zimbabwe",
  };
  const countryIDs: Record<CountryName, CountryID> = {
    Afghanistan: 1,
    "Åland Islands": 2,
    Albania: 3,
    Algeria: 4,
    "American Samoa": 5,
    Andorra: 6,
    Angola: 7,
    Anguilla: 8,
    Antarctica: 9,
    "Antigua and Barbuda": 10,
    Argentina: 11,
    Armenia: 12,
    Aruba: 13,
    Australia: 14,
    Austria: 15,
    Azerbaijan: 16,
    Bahamas: 17,
    Bahrain: 18,
    Bangladesh: 19,
    Barbados: 20,
    Belarus: 21,
    Belgium: 22,
    Belize: 23,
    Benin: 24,
    Bermuda: 25,
    Bhutan: 26,
    Bolivia: 27,
    "Bonaire, Sint Eustatius and Saba": 28,
    "Bosnia and Herzegovina": 29,
    Botswana: 30,
    "Bouvet Island": 31,
    Brazil: 32,
    "British Indian Ocean Territory": 33,
    "Brunei Darussalam": 34,
    Bulgaria: 35,
    "Burkina Faso": 36,
    Burundi: 37,
    Cambodia: 38,
    Cameroon: 39,
    Canada: 40,
    "Cape Verde": 41,
    "Cayman Islands": 42,
    "Central African Republic": 43,
    Chad: 44,
    Chile: 45,
    China: 46,
    "Christmas Island": 47,
    "Cocos (Keeling) Islands": 48,
    Colombia: 49,
    Comoros: 50,
    Congo: 51,
    "Congo, the Democratic Republic of the": 52,
    "Cook Islands": 53,
    "Costa Rica": 54,
    "Cote DIvoire": 55,
    Croatia: 56,
    Cuba: 57,
    Curaçao: 58,
    Cyprus: 59,
    "Czech Republic": 60,
    Denmark: 61,
    Djibouti: 62,
    Dominica: 63,
    "Dominican Republic": 64,
    Ecuador: 65,
    Egypt: 66,
    "El Salvador": 67,
    "Equatorial Guinea": 68,
    Eritrea: 69,
    Estonia: 70,
    Ethiopia: 71,
    "Falkland Islands (Malvinas)": 72,
    "Faroe Islands": 73,
    Fiji: 74,
    Finland: 75,
    France: 76,
    "French Guiana": 77,
    "French Polynesia": 78,
    "French Southern Territories": 79,
    Gabon: 80,
    Gambia: 81,
    Georgia: 82,
    Germany: 83,
    Ghana: 84,
    Gibraltar: 85,
    Greece: 86,
    Greenland: 87,
    Grenada: 88,
    Guadeloupe: 89,
    Guam: 90,
    Guatemala: 91,
    Guernsey: 92,
    Guinea: 93,
    "Guinea-Bissau": 94,
    Guyana: 95,
    Haiti: 96,
    "Heard Island and Mcdonald Islands": 97,
    "Holy See (Vatican City State)": 98,
    Honduras: 99,
    "Hong Kong": 100,
    Hungary: 101,
    Iceland: 102,
    India: 103,
    Indonesia: 104,
    "Iran, Islamic Republic of": 105,
    Iraq: 106,
    Ireland: 107,
    "Isle of Man": 108,
    Israel: 109,
    Italy: 110,
    Jamaica: 111,
    Japan: 112,
    Jersey: 113,
    Jordan: 114,
    Kazakhstan: 115,
    Kenya: 116,
    Kiribati: 117,
    "Korea, Democratic People's Republic of": 118,
    "Korea, Republic of": 119,
    Kuwait: 120,
    Kyrgyzstan: 121,
    "Lao People's Democratic Republic": 122,
    Latvia: 123,
    Lebanon: 124,
    Lesotho: 125,
    Liberia: 126,
    Libya: 127,
    Liechtenstein: 128,
    Lithuania: 129,
    Luxembourg: 130,
    Macao: 131,
    "Macedonia, the Former Yugoslav Republic of": 132,
    Madagascar: 133,
    Malawi: 134,
    Malaysia: 135,
    Maldives: 136,
    Mali: 137,
    Malta: 138,
    "Marshall Islands": 139,
    Martinique: 140,
    Mauritania: 141,
    Mauritius: 142,
    Mayotte: 143,
    Mexico: 144,
    "Micronesia, Federated States of": 145,
    "Moldova, Republic of": 146,
    Monaco: 147,
    Mongolia: 148,
    Montenegro: 149,
    Montserrat: 150,
    Morocco: 151,
    Mozambique: 152,
    Myanmar: 153,
    Namibia: 154,
    Nauru: 155,
    Nepal: 156,
    Netherlands: 157,
    "New Caledonia": 158,
    "New Zealand": 159,
    Nicaragua: 160,
    Niger: 161,
    Nigeria: 162,
    Niue: 163,
    "Norfolk Island": 164,
    "Northern Mariana Islands": 165,
    Norway: 166,
    Oman: 167,
    Pakistan: 168,
    Palau: 169,
    "Palestine, State of": 170,
    Panama: 171,
    "Papua New Guinea": 172,
    Paraguay: 173,
    Peru: 174,
    Philippines: 175,
    Pitcairn: 176,
    Poland: 177,
    Portugal: 178,
    "Puerto Rico": 179,
    Qatar: 180,
    Reunion: 181,
    Romania: 182,
    "Russian Federation": 183,
    Rwanda: 184,
    "Saint Barthélemy": 185,
    "Saint Helena, Ascension and Tristan da Cunha": 186,
    "Saint Kitts and Nevis": 187,
    "Saint Lucia": 188,
    "Saint Martin (French part)": 189,
    "Saint Pierre and Miquelon": 190,
    "Saint Vincent and the Grenadines": 191,
    Samoa: 192,
    "San Marino": 193,
    "Sao Tome and Principe": 194,
    "Saudi Arabia": 195,
    Senegal: 196,
    Serbia: 197,
    Seychelles: 198,
    "Sierra Leone": 199,
    Singapore: 200,
    "Sint Maarten (Dutch part)": 201,
    Slovakia: 202,
    Slovenia: 203,
    "Solomon Islands": 204,
    Somalia: 205,
    "South Africa": 206,
    "South Georgia and the South Sandwich Islands": 207,
    "South Sudan": 208,
    Spain: 209,
    "Sri Lanka": 210,
    Sudan: 211,
    Suriname: 212,
    "Svalbard and Jan Mayen": 213,
    Swaziland: 214,
    Sweden: 215,
    Switzerland: 216,
    "Syrian Arab Republic": 217,
    "Taiwan (Province of China)": 218,
    Tajikistan: 219,
    "Tanzania, United Republic of": 220,
    Thailand: 221,
    "Timor-Leste": 222,
    Togo: 223,
    Tokelau: 224,
    Tonga: 225,
    "Trinidad and Tobago": 226,
    Tunisia: 227,
    Turkey: 228,
    Turkmenistan: 229,
    "Turks and Caicos Islands": 230,
    Tuvalu: 231,
    Uganda: 232,
    Ukraine: 233,
    "United Arab Emirates": 234,
    "United Kingdom": 235,
    "United States": 236,
    "United States Minor Outlying Islands": 237,
    Uruguay: 238,
    Uzbekistan: 239,
    Vanuatu: 240,
    Venezuela: 241,
    "Viet Nam": 242,
    "Virgin Islands (British)": 243,
    "Virgin Islands (U.S.)": 244,
    "Wallis and Futuna": 245,
    "Western Sahara": 246,
    Yemen: 247,
    Zambia: 248,
    Zimbabwe: 249,
  };
  if (typeof input === "number") {
    if (input in countryLabels) {
      return countryLabels[input as keyof typeof countryLabels];
    } else throw new Error("Parameter is not a valid 'country_id' value");
  } else if (typeof input === "string") {
    if (input in countryIDs) {
      return countryIDs[input as keyof typeof countryIDs];
    } else throw new Error("Parameter is not a valid 'name' value");
  } else {
    throw new Error(
      "Parameter must be either a string or a number that matches a value dictated by either 'country_id' or 'name'"
    );
  }
}
/**
 * Determines the country's ISO 3166 country code from a string input of a country's name.
 * Used to determine a correct country code to be used with the OpenWeatherMap API endpoint and
 * guarantee that the country part of the request is correct. The locale is still subject
 * to the user entering correct information. If an invalid value is entered, this function
 * will throw an error, as it is critical to retrieving data accurately.
 * @param input {CountryName} The country name as a string that will be used to retrieve the
 * correct ISO code.
 * @returns {Database["countries"]["iso_code"]} The inputted country's ISO code, in string format.
 * @example
 * // Returns "AF"
 * getISOCodeFromCountry("Afghanistan")
 * // Returns "GB"
 * getISOCodeFromCountry("United Kingdom")
 */
export function getISOCodeFromCountry(input: CountryName): CountryISOCode {
  const lookupTable: Record<CountryName, CountryISOCode> = {
    Afghanistan: "AF",
    "Åland Islands": "AX",
    Albania: "AL",
    Algeria: "DZ",
    "American Samoa": "AS",
    Andorra: "AD",
    Angola: "AO",
    Anguilla: "AI",
    Antarctica: "AQ",
    "Antigua and Barbuda": "AG",
    Argentina: "AR",
    Armenia: "AM",
    Aruba: "AW",
    Australia: "AU",
    Austria: "AT",
    Azerbaijan: "AZ",
    Bahamas: "BS",
    Bahrain: "BH",
    Bangladesh: "BD",
    Barbados: "BB",
    Belarus: "BY",
    Belgium: "BE",
    Belize: "BZ",
    Benin: "BJ",
    Bermuda: "BM",
    Bhutan: "BT",
    Bolivia: "BO",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    "Bosnia and Herzegovina": "BA",
    Botswana: "BW",
    "Bouvet Island": "BV",
    Brazil: "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    Bulgaria: "BG",
    "Burkina Faso": "BF",
    Burundi: "BI",
    Cambodia: "KH",
    Cameroon: "CM",
    Canada: "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    Chad: "TD",
    Chile: "CL",
    China: "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    Colombia: "CO",
    Comoros: "KM",
    Congo: "CG",
    "Congo, the Democratic Republic of the": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Cote DIvoire": "CI",
    Croatia: "HR",
    Cuba: "CU",
    Curaçao: "CW",
    Cyprus: "CY",
    "Czech Republic": "CZ",
    Denmark: "DK",
    Djibouti: "DJ",
    Dominica: "DM",
    "Dominican Republic": "DO",
    Ecuador: "EC",
    Egypt: "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    Eritrea: "ER",
    Estonia: "EE",
    Ethiopia: "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    Fiji: "FJ",
    Finland: "FI",
    France: "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    Gabon: "GA",
    Gambia: "GM",
    Georgia: "GE",
    Germany: "DE",
    Ghana: "GH",
    Gibraltar: "GI",
    Greece: "GR",
    Greenland: "GL",
    Grenada: "GD",
    Guadeloupe: "GP",
    Guam: "GU",
    Guatemala: "GT",
    Guernsey: "GG",
    Guinea: "GN",
    "Guinea-Bissau": "GW",
    Guyana: "GY",
    Haiti: "HT",
    "Heard Island and Mcdonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    Honduras: "HN",
    "Hong Kong": "HK",
    Hungary: "HU",
    Iceland: "IS",
    India: "IN",
    Indonesia: "ID",
    "Iran, Islamic Republic of": "IR",
    Iraq: "IQ",
    Ireland: "IE",
    "Isle of Man": "IM",
    Israel: "IL",
    Italy: "IT",
    Jamaica: "JM",
    Japan: "JP",
    Jersey: "JE",
    Jordan: "JO",
    Kazakhstan: "KZ",
    Kenya: "KE",
    Kiribati: "KI",
    "Korea, Democratic People's Republic of": "KP",
    "Korea, Republic of": "KR",
    Kuwait: "KW",
    Kyrgyzstan: "KG",
    "Lao People's Democratic Republic": "LA",
    Latvia: "LV",
    Lebanon: "LB",
    Lesotho: "LS",
    Liberia: "LR",
    Libya: "LY",
    Liechtenstein: "LI",
    Lithuania: "LT",
    Luxembourg: "LU",
    Macao: "MO",
    "Macedonia, the Former Yugoslav Republic of": "MK",
    Madagascar: "MG",
    Malawi: "MW",
    Malaysia: "MY",
    Maldives: "MV",
    Mali: "ML",
    Malta: "MT",
    "Marshall Islands": "MH",
    Martinique: "MQ",
    Mauritania: "MR",
    Mauritius: "MU",
    Mayotte: "YT",
    Mexico: "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova, Republic of": "MD",
    Monaco: "MC",
    Mongolia: "MN",
    Montenegro: "ME",
    Montserrat: "MS",
    Morocco: "MA",
    Mozambique: "MZ",
    Myanmar: "MM",
    Namibia: "NA",
    Nauru: "NR",
    Nepal: "NP",
    Netherlands: "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    Nicaragua: "NI",
    Niger: "NE",
    Nigeria: "NG",
    Niue: "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    Norway: "NO",
    Oman: "OM",
    Pakistan: "PK",
    Palau: "PW",
    "Palestine, State of": "PS",
    Panama: "PA",
    "Papua New Guinea": "PG",
    Paraguay: "PY",
    Peru: "PE",
    Philippines: "PH",
    Pitcairn: "PN",
    Poland: "PL",
    Portugal: "PT",
    "Puerto Rico": "PR",
    Qatar: "QA",
    Reunion: "RE",
    Romania: "RO",
    "Russian Federation": "RU",
    Rwanda: "RW",
    "Saint Barthélemy": "BL",
    "Saint Helena, Ascension and Tristan da Cunha": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin (French part)": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    Samoa: "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    Senegal: "SN",
    Serbia: "RS",
    Seychelles: "SC",
    "Sierra Leone": "SL",
    Singapore: "SG",
    "Sint Maarten (Dutch part)": "SX",
    Slovakia: "SK",
    Slovenia: "SI",
    "Solomon Islands": "SB",
    Somalia: "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Sudan": "SS",
    Spain: "ES",
    "Sri Lanka": "LK",
    Sudan: "SD",
    Suriname: "SR",
    "Svalbard and Jan Mayen": "SJ",
    Swaziland: "SZ",
    Sweden: "SE",
    Switzerland: "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan (Province of China)": "TW",
    Tajikistan: "TJ",
    "Tanzania, United Republic of": "TZ",
    Thailand: "TH",
    "Timor-Leste": "TL",
    Togo: "TG",
    Tokelau: "TK",
    Tonga: "TO",
    "Trinidad and Tobago": "TT",
    Tunisia: "TN",
    Turkey: "TR",
    Turkmenistan: "TM",
    "Turks and Caicos Islands": "TC",
    Tuvalu: "TV",
    Uganda: "UG",
    Ukraine: "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    Uruguay: "UY",
    Uzbekistan: "UZ",
    Vanuatu: "VU",
    Venezuela: "VE",
    "Viet Nam": "VN",
    "Virgin Islands (British)": "VG",
    "Virgin Islands (U.S.)": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    Yemen: "YE",
    Zambia: "ZM",
    Zimbabwe: "ZW",
  };
  if (input in lookupTable) {
    return lookupTable[input];
  } else {
    throw new Error("Parameter is not a valid 'name' value");
  }
}
